# SPDX-FileCopyrightText: 2018 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: "Thanks for opening your first pull request in this repository! :v:"
