# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
comment: false
coverage:
  status:
    project:
      unit:
        target: auto
        flags:
          - unittests
      integration:
        target: auto
        flags:
          - integrationtests
ignore:
  - "tests"
  - "lib/Vendor"
