[package]
before_cmds = [
	"composer install --no-dev -o",
	"npm install --deps",
	"npm run build",
]

exclude = [
	"bower.json",
	".bowerrc",
	"build",
	"composer.json",
	"composer.lock",
	"composer.phar",
	"CONTRIBUTING.md",
	"coverage",
	".git",
	".gitattributes",
	".github",
	".gitignore",
	"Gruntfile.js",
	".hg",
	"issue_template.md",
	".jscsrc",
	".jshintignore",
	".jshintrc",
	"js/controller",
	"js/models",
	"js/service",
	"js/templatehelpers",
	"js/templates",
	"js/tests",
	"js/util",
	"js/views",
	"js/webpack.*.js",
	"karma.conf.js",
	"l10n/no-php",
	"l10n/.tx",
	"Makefile",
	"nbproject",
	"node_modules",
	"package.json",
	".phan",
	"phpunit*xml",
	"screenshots",
	".scrutinizer.yml",
	"tests",
	".travis.yml",
	"vendor/bin",
]
