name: "Feature request"
description: "You have a neat idea that should be implemented?"
type: "Enhancement"
labels: ["enhancement", "0. to triage"]
body:
  - type: textarea
    id: description-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
          A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: description-solution
    attributes:
      label: Describe the solution you'd like
      description: |
          A clear and concise description of what you want to happen.
  - type: textarea
    id: description-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
          A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
          Add any other context or screenshots about the feature request here.
