# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2021-2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Generate changelog

on: pull_request

env:
  PHP_VERSION: 8.2

jobs:
  build_and_publish:
    runs-on: [ubuntu-latest, self-hosted]

    steps:
      - name: Set app env
        run: |
          # Split and keep last
          echo "APP_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@b7f32a8347e86c26ea2f4823cc7c160b9014c6a0 # v3
        with:
          github-token: ${{ secrets.RELEASE_PAT }}
          git-user-email: nextcloud-command@users.noreply.github.com
          git-user-name: Nextcloud Command Bot
          skip-git-pull: "true"
          skip-tag: "true"
          git-push: "false"
          pre-commit: build/pre-commit.js
          release-count: 0
          version-file: "package.json, package-lock.json"
          pre-release: ${{ inputs.prerelease }}
          pre-release-identifier: ${{ inputs.prereleaseIdentifier }}
