# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Pull request checks

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  commit-message-check:
    name: Block fixup and squash commits
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Run check
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
