# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2024 Arthur Schiwon <blizzz@arthur-schiwon.de>
# SPDX-License-Identifier: MIT

name: OpenAPI

on: pull_request

permissions:
  contents: read

concurrency:
  group: openapi-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  openapi:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get php version
        id: php_versions
        uses: icewind1991/nextcloud-version-matrix@58becf3b4bb6dc6cef677b15e2fd8e7d48c0908f # v1.3.1

      - name: Set up php
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # 2.31.1
        with:
          php-version: ${{ steps.php_versions.outputs.php-available }}
          extensions: xml
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Typescript OpenApi types
        id: check_typescript_openapi
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "src/types/openapi/openapi*.ts"

      - name: Read package.json node and npm engines version
        if: steps.check_typescript_openapi.outputs.files_exists == 'true'
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: node_versions
        # Continue if no package.json
        continue-on-error: true
        with:
          fallbackNode: '^20'
          fallbackNpm: '^10'

      - name: Set up node ${{ steps.node_versions.outputs.nodeVersion }}
        if: ${{ steps.node_versions.outputs.nodeVersion }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ steps.node_versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.node_versions.outputs.npmVersion }}
        if: ${{ steps.node_versions.outputs.nodeVersion }}
        run: npm i -g 'npm@${{ steps.node_versions.outputs.npmVersion }}'

      - name: Install dependencies & build
        if: ${{ steps.node_versions.outputs.nodeVersion }}
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: |
          npm ci

      - name: Set up dependencies
        run: composer i

      - name: Regenerate OpenAPI
        run: composer run openapi
